import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import { Navigation } from 'swiper'
import 'swiper/css';
import pageContent from "../site/home.yml";


export default function Home() {
  // destructure.
  const { about, address, desktopImages, hours, contact, menu_philosophy, menu, order_online_link, book_online_link } = pageContent;
  console.log(desktopImages)

  return (
    <div className="flex h-dvh overflow-hidden flex-col bg-green text-cream">
     
     <div>
      <div className="relative z-[3]">
        
      </div>

     </div>
    </div>
  )
}

// <div className={styles.container}>
//   <Head>
//     <title>Create Next App</title>
//     <meta name="description" content="Generated by create next app" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>


//   <main className={styles.main}>

    


//   </main>

//   <footer className={styles.footer}>
   
//   </footer>
// </div>
{/* <div>{about}</div>
<div>{address}</div>
<MarkdownComponent content ={hours} />
<div>{contact}</div>
<div>{menu_philosophy}</div>
<div>{menu}</div>
<div>{order_online_link}</div>
<div>{book_online_link}</div> */}

// Get images working
// add tailwind
// get click/slider working. 

