import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
// import { Navigation } from 'swiper'
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import { SwiperNavButton } from '../components/SwiperNavButton';
import { EffectFade } from 'swiper/modules';


import pageContent from "../site/home.yml";


export default function Home() {
  // destructure.
  const { about, address, desktopImages, hours, contact, menu_philosophy, menu, order_online_link, book_online_link } = pageContent;
  console.log(desktopImages)

  return (
    <div className="flex h-dvh overflow-hidden flex-col bg-green text-cream">
     
     <div>
      <div className="relative z-[3]">
      <Swiper
        spaceBetween={50}
        slidesPerView={1}
        allowTouchMove={false}
        onSlideChange={() => console.log('slide change')}
        onSwiper={(swiper) => console.log(swiper)}
        loop={true}
        effect={'fade'}
        modules={[EffectFade]}

      >
        {desktopImages.map((image, index) => (
          <div key={index} className="m-2">
            <SwiperSlide key={index}> 
              <Image
                src={image}
                width={1920}  // Set the actual width of the image
                height={1080} // Set the actual height of the image
              /> 
            </SwiperSlide>
           
          </div>
        ))}
       
       <SwiperNavButton />
        {/* <button class="absolute top-[0px] left-[0px] z-[33] h-[100vh] w-[100vw]"></button> */}
      </Swiper>
      </div>

     </div>
    </div>
  )
}

// <div className={styles.container}>
//   <Head>
//     <title>Create Next App</title>
//     <meta name="description" content="Generated by create next app" />
//     <link rel="icon" href="/favicon.ico" />
//   </Head>


//   <main className={styles.main}>

    


//   </main>

//   <footer className={styles.footer}>
   
//   </footer>
// </div>
{/* <div>{about}</div>
<div>{address}</div>
<MarkdownComponent content ={hours} />
<div>{contact}</div>
<div>{menu_philosophy}</div>
<div>{menu}</div>
<div>{order_online_link}</div>
<div>{book_online_link}</div> */}

// Get images working
// add tailwind
// get click/slider working. 

